# browser/__init__.pyi
from typing import Any, Callable

# ---------- Événements ----------
class DOMEvent:
    target: Any
    type: str


# ---------- DOM Element ----------
class DOMElement:
    id: str
    class_name: str
    style: dict[str, Any]
    text: str
    html: str
    value: str
    checked: bool
    attrs: dict[str, Any]

    def bind(self, event: str, callback: Callable[[Any], None]) -> None: ...
    def unbind(self, event: str) -> None: ...
    def append(self, child: "DOMElement") -> None: ...
    def remove(self) -> None: ...
    def __le__(self, other: "DOMElement") -> None: ...
    def __getitem__(self, key: str) -> "DOMElement": ...
    def __setitem__(self, key: str, value: Any) -> None: ...

    width: float
    height: float
    
# ---------- Document ----------
class Document:
    def __getitem__(self, key: str) -> DOMElement: ...
    def __setitem__(self, key: str, value: Any) -> None: ...

document: Document


# ---------- Window ----------
class Window:
    def alert(self, message: str) -> None: ...
    def confirm(self, message: str) -> bool: ...
    def prompt(self, message: str, default: str = "") -> str: ...

    def console_log(self, message: str) -> None: ...

    def set_timeout(self, func: Callable[[], None], delay: int) -> int: ...
    def clear_timeout(self, timer_id: int) -> None: ...

    def set_interval(self, func: Callable[[], None], delay: int) -> int: ...
    def clear_interval(self, timer_id: int) -> None: ...

    def bind(self, event: str, callback: Callable[[Any], None]) -> None: ...


window: Window


# ---------- Fonctions globales ----------
def alert(message: str) -> None: ...
def confirm(message: str) -> bool: ...
def prompt(message: str, default: str = "") -> str: ...

def console_log(message: str) -> None: ...

def set_timeout(func: Callable[[], None], delay: int) -> int: ...
def clear_timeout(timer_id: int) -> None: ...

def set_interval(func: Callable[[], None], delay: int) -> int: ...
def clear_interval(timer_id: int) -> None: ...
