# browser/html.pyi
from typing import Any, Callable, Union

# ---------- Type pour les enfants ----------
ChildType = Union[str, "HTMLElement"]


# ---------- Événement ----------
class DOMEvent:
    target: Any
    type: str


# ---------- Base de tous les éléments ----------
class HTMLElement:
    id: str
    class_name: str
    style: dict[str, Any]
    text: str
    html: str
    attrs: dict[str, Any]

    def bind(self, event: str, callback: Callable[[Any], None]) -> None: ...
    def unbind(self, event: str) -> None: ...
    def append(self, child: "HTMLElement") -> None: ...
    def remove(self) -> None: ...
    def __le__(self, other: "HTMLElement") -> None: ...
    def __getitem__(self, key: str) -> "HTMLElement": ...
    def __setitem__(self, key: str, value: Any) -> None: ...

# ---------- Éléments HTML ----------
class DIV(HTMLElement):
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class SPAN(HTMLElement):
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class BUTTON(HTMLElement):
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class INPUT(HTMLElement):
    value: str
    checked: bool
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class TEXTAREA(HTMLElement):
    value: str
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class SELECT(HTMLElement):
    value: str
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class OPTION(HTMLElement):
    selected: bool
    value: str
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class LABEL(HTMLElement):
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class UL(HTMLElement):
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class LI(HTMLElement):
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class FORM(HTMLElement):
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class IMG(HTMLElement):
    src: str
    alt: str
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class A(HTMLElement):
    href: str
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...


# ---------- Titres ----------
class H1(HTMLElement): ...
class H2(HTMLElement): ...
class H3(HTMLElement): ...
class H4(HTMLElement): ...
class H5(HTMLElement): ...
class H6(HTMLElement): ...


# ---------- Table ----------
class TABLE(HTMLElement): ...
class TR(HTMLElement): ...
class TD(HTMLElement): ...
class TH(HTMLElement): ...


# ---------- SVG ----------
class SVG(HTMLElement):
    width: float
    height: float
    html: str
    def __init__(self, *children: ChildType, **attrs: Any) -> None: ...

class CANVAS(HTMLElement): ...


# ---------- Médias ----------
class VIDEO(HTMLElement): ...
class AUDIO(HTMLElement): ...
class SOURCE(HTMLElement): ...


# ---------- Divers ----------
class BR(HTMLElement): ...
class HR(HTMLElement): ...