# browser/timer.pyi
from typing import Callable

def set_timeout(func: Callable[[], None], delay: int) -> int: ...
def clear_timeout(timer_id: int) -> None: ...

def set_interval(func: Callable[[], None], delay: int) -> int: ...
def clear_interval(timer_id: int) -> None: ...